run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - gofmt
    - gosimple
    - staticcheck
    - unused
    - deadcode
    - structcheck
    - varcheck
    - gocognit

linters-settings:
  gocognit:
    min-complexity: 10

issues:
  exclude-rules:
    - path: cmd/server/main.go
      linters:
        - errcheck

output:
  print-issued-lines: true
