services:
  eventstore:
    image: eventstore/eventstore:latest
    container_name: eventstore
    ports:
      - "2113:2113" # HTTP interface
      - "1113:1113" # TCP interface
    environment:
      EVENTSTORE_RUN_PROJECTIONS: All
      EVENTSTORE_START_STANDARD_PROJECTIONS: "true"
      EVENTSTORE_HTTP_PORT: 2113
      EVENTSTORE_INSECURE: "true" # NOTE: insecure mode for development

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: go_app
    ports:
      - "8080:8080"
    environment:
      APP_ENV: development
      EVENTSTORE_URL: http://eventstore:2113
    depends_on:
      - eventstore
    volumes:
      - .:/app
